//
// Created by Valerij Primachenko on 20-07-01.
//

#ifndef DAS_EFFECT_H
#define DAS_EFFECT_H

namespace DAS {
	enum class Effect {
		PASSIVE_NONE, PASSIVE_SET, PASSIVE_BLINK, PASSIVE_BREATHE, PASSIVE_COLOR_CYCLE,
		ACTIVE_NONE, ACTIVE_SET, ACTIVE_BLINK, ACTIVE_BREATHE, ACTIVE_COLOR_CYCLE, ACTIVE_RIPPLE, ACTIVE_INV_RIPPLE, ACTIVE_LASER
	};
}

#endif //DAS_EFFECT_H
